### ISSUE TITLE
Upgrade to Postgres 14 (requires fixing issue with Kong bootstrapping)

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#4028]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
Need to stay up to date with latest released version

### Description [**REQUIRED**]
Kong doesn't bootstrap when using Postgres 14.3

**With Kong 2.6 we get these logs:**
```
level=INFO ts=2022-05-18T18:44:47.667134393Z app=security-bootstrapper source=command.go:187 msg="File file:///tmp/postgres-config/.pgpassword had been generated"
Wed May 18 18:44:47 UTC 2022 Check point: postgres db is ready for kong
Error: don't know how to auth: 10

  Run with --v (verbose) or --vv (debug) for more details
```

**With Kong 2.8 we get these logs:**
```
,level=INFO ts=2022-05-18T18:36:16.283718231Z app=security-bootstrapper source=command.go:187 msg="File file:///tmp/postgres-config/.pgpassword had been generated"
,	no file '/usr/local/openresty/site/lualib/openssl/rand.ljbc'
,Wed May 18 18:36:16 UTC 2022 Check point: postgres db is ready for kong
,level=INFO ts=2022-05-18T18:36:15.283161546Z app=security-bootstrapper source=command.go:144 msg="Waiting for: [file:///tmp/postgres-config/.pgpassword] with timeout: [1m0s]"
,Error: module 'openssl.rand' not found:No LuaRocks module found for openssl.rand
,	no field package.preload['openssl.rand']
,	no file './openssl/rand.lua'
,	no file './openssl/rand/init.lua'
,	no file '/usr/local/openresty/site/lualib/openssl/rand/init.ljbc'
,	no file '/usr/local/openresty/lualib/openssl/rand.ljbc'
,	no file '/usr/local/openresty/lualib/openssl/rand/init.ljbc'
,	no file '/usr/local/openresty/site/lualib/openssl/rand/init.lua'
,	no file '/usr/local/openresty/lualib/openssl/rand.lua'
,	no file '/usr/local/openresty/site/lualib/openssl/rand.lua'
,	no file '/usr/local/openresty/lualib/openssl/rand/init.lua'
,	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/openssl/rand.lua'
,	no file '/usr/local/share/lua/5.1/openssl/rand.lua'
,	no file '/usr/local/share/lua/5.1/openssl/rand/init.lua'
,	no file '/usr/local/openresty/luajit/share/lua/5.1/openssl/rand.lua'
,	no file '/usr/local/openresty/luajit/share/lua/5.1/openssl/rand/init.lua'
,	no file '/home/kong/.luarocks/share/lua/5.1/openssl/rand.lua'
,	no file '/home/kong/.luarocks/share/lua/5.1/openssl/rand/init.lua'
,	no file '/usr/local/openresty/site/lualib/openssl/rand.so'
,	no file '/usr/local/openresty/lualib/openssl/rand.so'
,	no file './openssl/rand.so'
,	no file '/usr/local/lib/lua/5.1/openssl/rand.so'
,	no file '/usr/local/openresty/luajit/lib/lua/5.1/openssl/rand.so'
,	no file '/usr/local/lib/lua/5.1/loadall.so'
,	no file '/home/kong/.luarocks/lib/lua/5.1/openssl/rand.so'
,	no file '/usr/local/openresty/site/lualib/openssl.so'
,	no file '/usr/local/openresty/lualib/openssl.so'
,	no file './openssl.so'
,	no file '/usr/local/lib/lua/5.1/openssl.so'
,	no file '/usr/local/openresty/luajit/lib/lua/5.1/openssl.so'
,	no file '/home/kong/.luarocks/lib/lua/5.1/openssl.so'

Run with --v (verbose) or --vv (debug) for more details
```

### Describe the solution you'd like
Fix issue with boostraping of Kong with Postgres 14.x

### Describe alternatives you've considered
Stay with Postgres 13.x

**Comment by farshidtz** [comment]
Will the upgrade be backward compatible with respect to the user data?

In the snap, we had to develop a backup+restore process to migrate the user data when upgrading between postgres major versions:
https://github.com/edgexfoundry/edgex-go/blob/87560f2f4565905b4987d66a8308e965001c5142/snap/local/runtime-helpers/bin/kong-postgres-setup.sh#L205-L240

**Comment by bnevis-i** [comment]
@lenny-intel based on Farshid's feedback, and that Postgres 13 will be supported until November 13, 2025, I'd like to postpone this to EdgeX 3.0.

**Comment by lenny-intel** [comment]
@bnevis-i , iceboxed.

**Comment by bnevis-i** [comment]
See related issue in Kong's database: https://github.com/Kong/kong/issues/8259

**Comment by drkfmorton** [comment]
No errors and services loaded successfully, Kong 2.8 and Postgres 14.3
![image](https://user-images.githubusercontent.com/9958330/183809966-b34db069-fcfa-4318-8738-59b0fbbf45e6.png)

No errors and services loaded successfully, Kong 2.6 and Postgres 14.3
![image](https://user-images.githubusercontent.com/9958330/183810031-f78c070f-e68c-475c-9b09-6ced686fb078.png)

This may have been resolved as there has been a few postgres releases since this issue was reported.

**Comment by lenny-intel** [comment]
@drkfmorton , you need to look at the logs for Kong and Proxy setup to make sure they don't have errors. Then you need to send requests to one of the services, Core Data, via the API Gateway (aka Kong). 

Note there is an issue using API Gateway when running from WSL. To make it work you must remove the following line from Kong in the generated compose file.
```
KONG_DNS_VALID_TTL: '1'
```
 Use `make up` to run the modified generated compose file, otherwise `run` will regenerate and overwrite your modifications.

**Comment by bnevis-i** [comment]
Kyle confirmed this is still an issue.  Will not be able to fix in Levski release.  Re-examine next release cycle to see if Kong has fixed the issue.

**Comment by bnevis-i** [comment]
Issue no longer occurs with the new Kong 3.0 release as per https://github.com/edgexfoundry/edgex-compose/pull/292
